### ISSUE TITLE
见过学校大佬！！！！

### ISSUE THREAD

**Issue by takumi913** [muzhiyun/xsyudogcom#2]
！！！！！！！！！！！

**Comment by GatesSecond** [comment]
这个可以提高学校的网速吗？求解：）

**Comment by takumi913** [comment]
> 这个可以提高学校的网速吗？求解:)

很负责任的告诉你，并不会，我们学校的校园网是账号限速的，这个项目只能起到让你能够同时手机电脑都能上网的作用，对网速并没有帮助

**Comment by GatesSecond** [comment]
咱们学校之前有一个大四的学生好像在找工作经验交流会上说他好像用了什么技术可以一个哆点账号拥有四个账号的网速。有人弄过这个，我不知道。

**Comment by takumi913** [comment]
多播，但是现在哆点应该不能单线多播吧。。。我只知道可以同时登录几个账号叠加网速，，，一个账号拥有四个账号网速我觉得不太行，我们学校每个账号的速度都限制在8M,而且哆点同时也只允许一台设备登录，我觉得那个学长说的可能是几个账号叠加网速，这个是可以的




------------------ 原始邮件 ------------------
发件人: "Bruce Lee"<notifications@github.com>; 
发送时间: 2019年9月15日(星期天) 晚上7:14
收件人: "muzhiyun/xsyudogcom"<xsyudogcom@noreply.github.com>; 
抄送: "只想安静的做个呆子"<liyy0824@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [muzhiyun/xsyudogcom] 见过学校大佬！！！！ (#2)




咱们学校之前有一个大四的学生好像在找工作经验交流会上说他好像用了什么技术可以一个哆点账号拥有四个账号的网速。有人弄过这个，我不知道。

**Comment by GatesSecond** [comment]
网速叠加？这个是怎么实现的？需要黑进人家的网络给自己添加账号信息吗？：）

**Comment by takumi913** [comment]
不需要，改路由器，网上有教程，但是我没有搞这个，一个账号一个月二十，叠加四个账号一个月就80了，素的也快不到哪里去，有那么多钱，不如买张无限流量卡




------------------ 原始邮件 ------------------
发件人: "Bruce Lee"<notifications@github.com>; 
发送时间: 2019年9月15日(星期天) 晚上8:50
收件人: "muzhiyun/xsyudogcom"<xsyudogcom@noreply.github.com>; 
抄送: "只想安静的做个呆子"<liyy0824@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [muzhiyun/xsyudogcom] 见过学校大佬！！！！ (#2)




网速叠加？这个是怎么实现的？需要黑进人家的网络给自己添加账号信息吗？：）
 
&mdash;

**Comment by cry-t** [comment]
> > 这个可以提高学校的网速吗？求解:)
> 
> 很负责任的告诉你，并不会，我们学校的校园网是账号限速的，这个项目只能起到让你能够同时手机电脑都能上网的作用，对网速并没有帮助



> 咱们学校之前有一个大四的学生好像在找工作经验交流会上说他好像用了什么技术可以一个哆点账号拥有四个账号的网速。有人弄过这个，我不知道。

负载均衡    多wan口登录

**Comment by takumi913** [comment]
> > > 这个可以提高学校的网速吗？求解:)
> > 
> > 
> > 很负责任的告诉你，并不会，我们学校的校园网是账号限速的，这个项目只能起到让你能够同时手机电脑都能上网的作用，对网速并没有帮助
> 
> > 咱们学校之前有一个大四的学生好像在找工作经验交流会上说他好像用了什么技术可以一个哆点账号拥有四个账号的网速。有人弄过这个，我不知道。
> 
> 负载均衡 多wan口登录

多wan口登陆需要多个账号了吧。。。这成本也太高了
